language: python  
python:  
- '3.5'

branches:  
  only:  
  - src

install:  
- pip install -r requirements.txt
 
script:  
- make travis 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: false
  on:
    branch: master